package com.iss.weisdk.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.iss.weisdk.dao.TestEntity;

import com.iss.weisdk.dao.TestEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testEntityDaoConfig;

    private final TestEntityDao testEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testEntityDaoConfig = daoConfigMap.get(TestEntityDao.class).clone();
        testEntityDaoConfig.initIdentityScope(type);

        testEntityDao = new TestEntityDao(testEntityDaoConfig, this);

        registerDao(TestEntity.class, testEntityDao);
    }
    
    public void clear() {
        testEntityDaoConfig.getIdentityScope().clear();
    }

    public TestEntityDao getTestEntityDao() {
        return testEntityDao;
    }

}
