package com.iss.weisdk.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEST_ENTITY.
 */
public class TestEntity {

    private Long id;
    private String TestId;
    private String Name;

    public TestEntity() {
    }

    public TestEntity(Long id) {
        this.id = id;
    }

    public TestEntity(Long id, String TestId, String Name) {
        this.id = id;
        this.TestId = TestId;
        this.Name = Name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTestId() {
        return TestId;
    }

    public void setTestId(String TestId) {
        this.TestId = TestId;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

}
